config-ver: 1.1
bot-token: 'Insert token here'
bot-playing: 'Minecraft'
script-imports:
  - java.lang.*
  - java.utils.*
  - org.bukkit.*
  - org.bukkit.block.*
  - org.bukkit.entity.*
  - org.bukkit.inventory.*
  - org.bukkit.material.*
  - org.bukkit.map.*
  - org.bukkit.util.*
  - org.bukkit.scheduler.*
  - org.bukkit.plugin.*
  - org.bukkit.scoreboard.*
  - net.dv8tion.jda.core.*
  - net.dv8tion.jda.core.hooks.*
  - net.dv8tion.jda.core.utils.*
  - net.dv8tion.jda.core.events.message.*
  - net.dv8tion.jda.core.events.guild.*
  - net.dv8tion.jda.core.events.channel.*
  - net.dv8tion.jda.core.events.*
  - net.dv8tion.jda.core.entities.*
  - net.dv8tion.jda.bot.*
  - net.dv8tion.jda.client.*
  - org.bukkit.event.*
  - org.bukkit.entity.*
  - org.bukkit.event.player.*
  - org.bukkit.event.block.*
  - org.bukkit.event.entity.*
  - org.bukkit.event.enchantment.*
  - org.bukkit.event.hanging.*
  - org.bukkit.event.inventory.*
  - org.bukkit.event.server.*
  - org.bukkit.event.vehicle.*
  - org.bukkit.event.world.*
  - me.vrcube.scriptbot.*
  - org.codehaus.groovy.jsr223.*
  - javax.script.*
commands:
  '!ping':
    type: MSG
    message: 'hello'
event-script: 'none'
jda-event-script: 'none'
metrics-enabled: true

enable-script: 'none'
disable-script: 'none'
discord-command:
  messages:
  - '&c-------------------------------------------------'
  - '&eJoin our discord now: https://discord.gg/example'
  - '&ePowered by ScriptBot'
  - '&c-------------------------------------------------'
  enabled: true
